version: "3.7"

services:
  quarkus-service-a:
    build:
      context: ./microservice_a
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/microservice_a-jvm
    ports:
      - "8080:8080" 
      
  quarkus-service-b:      
    build:
      context: ./microservice_b
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/microservice_b-jvm
    environment:
      SERVICE_A: http://quarkus-service-a:8080
    ports:
      - "8090:8090"  
    depends_on:
       - quarkus-service-a